import logging
from pathlib import Path

from config.settings.base.logging import LogGuardConfig

from ..exceptions import guard
from ..exceptions.io import CoreIOException
from . import IO_LOGGER


log = logging.getLogger(IO_LOGGER)


def read_from_disk(path: Path, panic: bool = True, log_errors: bool = True) -> str:
    """
    Read from a file.
    Return the content of the file as a string.
    Return an empty string if the file does not exist or if an error occurred. - or of course: if the file is empty.
    """

    empty = ""
    lgcfg = LogGuardConfig(logger_name=IO_LOGGER, log_errors=log_errors)

    if not isinstance(path, Path):
        guard.exception(exc=TypeError(f"Invalid type for path: {type(path)=}"), panic=panic, lgcfg=lgcfg)
        return empty

    if not path.exists():
        guard.exception(exc=FileNotFoundError(f"{path} does not exist."), panic=panic, lgcfg=lgcfg)
        return empty

    if not path.is_file():
        guard.exception(exc=ValueError(f"{path} is not a file."), panic=panic, lgcfg=lgcfg)
        return empty

    try:
        with open(path) as file:
            content = file.read()
        log.debug(f"INOUT.FILES.READ {len(content)=} {path=}")
        return content
    except PermissionError as e:
        exc = CoreIOException("A permission error occurred while reading the file.", parent=e)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    except OSError as e:
        exc = CoreIOException("An OS error occurred while reading the file.", parent=e)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    except Exception as e:
        exc = CoreIOException("An unexpected error occurred.", parent=e)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    return empty


def write_to_disk(
    path: Path, content: str | bytes, panic: bool = True, log_errors: bool = True
) -> bool:
    """
    Write to a file.

    returns "success" True if the file was written successfully, False otherwise.
    """
    success: bool = False
    lgcfg = LogGuardConfig(logger_name=IO_LOGGER, log_errors=log_errors)
    content_type = type(content)

    if content_type is not bytes and content_type is not str:
        exc = TypeError(f"Content must be a string or bytes, not {content_type}")
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
        return success

    mode = "w" if content_type is str else "wb"

    if not isinstance(path, Path):
        exc =  TypeError(f"Invalid type for path: {type(path)=}")
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
        return success

    try:
        with open(file=path, mode=mode) as file:
            log.debug(f"INOUT.FILES.WRITE {len(content)=} {path=}")
            file.write(content)
            success = True
    except PermissionError as exc:
        exc = CoreIOException("A permission error occurred while writing the file.", parent=exc)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    except OSError as exc:
        exc = CoreIOException("An OS error occurred while writing the file.", parent=exc)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    except Exception as exc:
        exc = CoreIOException("An unexpected error occurred while writing the file.", parent=exc)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    return success


def unlink(path: Path, panic: bool = True, log_errors: bool = True) -> bool:
    """Delete a file."""
    success = False
    lgcfg = LogGuardConfig(logger_name=IO_LOGGER, log_errors=log_errors)

    if not isinstance(path, Path):
        exc = TypeError(f"Invalid type for path: {type(path)=}")
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
        return success

    try:
        path.unlink()
        success = True
    except PermissionError as exc:
        exc = CoreIOException("A permission error occurred while deleting the file.", parent=exc)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    except OSError as exc:
        exc = CoreIOException("An OS error occurred while deleting the file.", parent=exc)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    except Exception as exc:
        exc = CoreIOException("An unexpected error occurred while deleting the file.", parent=exc)
        guard.exception(exc=exc, panic=panic, lgcfg=lgcfg)
    return success
